services:
    davidiq.advancedguestposting.listener:
        class: davidiq\advancedguestposting\event\main_listener
        arguments:
            - '@request'
            - '@language'
        tags:
            - { name: event.listener }
